# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7-fpm

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y git curl libmcrypt-dev mysql-client
          - pecl install mcrypt-1.0.1
          - docker-php-ext-enable mcrypt
          - docker-php-ext-install pdo_mysql
          - ./install-composer.sh
          - composer install
          - export CACHE_DRIVER=redis
          - export SESSION_DRIVER=redis
          - export DB_CONNECTION=mysql
          - php artisan migrate --database=system
          - php artisan migrate --database=tenant --path=./database/migrations/tenant
          - php artisan db:seed --database=system --class=InstituteTableSeeder
          - php artisan db:seed --database=tenant
          - php artisan serve &
          - sleep 5
          - curl -vk http://localhost:8000
          - vendor/bin/phpunit
        services:
          - system-db
          - tenant-db

definitions:
  services:
    system-db:
      image: mysql
      environment:
        MYSQL_DATABASE: 'tuitionix_system_test'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'www'
        MYSQL_PASSWORD: 'wwwpwd'
    tenant-db:
      image: mysql
      environment:
        MYSQL_DATABASE: 'tuitionix_tenant_test'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'www'
        MYSQL_PASSWORD: 'wwwpwd'
